Develop -> Main (#108)
* feat: adding file to connect to postgresql database and creating files to make all folders tracked

* feat: changing commments to English not in pt-br

* feat: adding a service to send emails, also creating a Config Service to connect to take the environment variables, and changing the Connection with postgre file

* feat: adding another method with the same name, but without a filePath in parameters

* feat: removing a emoji in an exception, also changing the sender of email name

* feat: creating models for database tables (#17)

* refactor: rename user to student

* feat: implementing the Subject model

* feat: implementing the StudentSubject model

* feat: implementing the Admin model

* feat(Admin): add constructors methods

* feat(Student): add constructors methods

* feat(StudentSubject): add constructors methods

* feat(Subject): add constructors methods

* feat: adding id and creating methods in adminDAO

* feat: adding some documentation in GenericDAO

* feat(AdminDAO): fixing comments

* feat(OutputFormat): creating a class to transform the data in database to another shape for the output

* feat(OutputFormat): adding a method to format cpf to output

* feat: adding validation to see if the parameter is not null, also moving enrollment to Student class

* feat: adding validation to see if the parameter is not null, also moving enrollment to Student class

* feat(regex): creating a file to be a service that validates all fields of database

* feat(regex): removing an extra file

* feat(regex): fixing some deleted files that are not deleted locally

* feat: fixing cpd wrote in a comment of RegexService to cpf

* feat(validationService): adding validations to enrollment and grade, also changing the password's validation

* feat(ValidationService): adding a password validation enum, and increasing perfomance of validate password

* feat: changing int enrollment inputed to string

* feat: adding some validations

* Feature/24

* fix: add constructor and setter for teacherPassword in Subject.java

* feat: implement SubjectDAO with CRUD operations and pagination support

* fix: Logic improvement

* fix: improve logic and organization

* feat(StudentSubject): creating and implementing CRUD's methods, also fixing a problem in GenericDAO and PostgreConnection

* feat: making changes to connect to new database

* feat(InputNormalizer): creting a class that has static methods to transform the shape of the user's input to the format defined in the business' rule

* feat(InputNormalizer): adding a method to normalize cpf

* feat: adding .trim() in input normalizer

* feat: validating if input is null or not

* feat: fixing documentation of the methods

* refactor: chaging DAO and models to be equal as our new database schema

* refactor: chaging student subject

* fix: solving an error in deadline atribute name

* feat(loginAdmin): creating a servlet to login admins, also making changes in how we connect to databse by using HikariCP

* feat(adminLogin): merging with develop and rebase

* Feature/29 

* feat: new model: Teacher

* feat: new DAO: TeacherDAO

* fix: right usage of parameters. Class: TeacherDAO.java

* fix: improve TeacherDAO's coherence

* fix: improve TeacherDAO's coherence

* fix: improve TeacherDAO's coherence: rename parameters

* feat(forgotPassword): creating servlets, changing some DAO's methods and making some basic .jsp pages

* feat(forgotPassword): adding teacher's DAO in forgot password's files

* feat(constants): creating a file with all constants

* feat(constants): adding a default_take

* feat(student): fixing student's model, making its DAO, fixing servlet of forgot password and creating a login servlet for teacher and student

* feat(student): fixing a possible problem in login servlet

* feat(student): fixing some problems

* Add the table School_Class

* feat: implement table school_class (feature/49)

* feat: implement table subject_teacher (feature/50)

* feat: new servlet; administrators now can sign up students 

* feat: new servlet; administrators now can sign up students

* fix: improve input validation and treats unique violation

* fix: Make strings and variables dynamic

* feat: creating relation SchollClassTeacher

* feat(schoolClassTeacher): creating a model for that table, also creating  a DAO

* feat: solving comments in my pull request

* feat: solving mari's comments

* feat(exceptions): adding exceptions to catch possible errors

* feat(exceptions): adding some validations, and exceptions, also fixing a possivble use of input to map who is user and who is not

* feat: fixing some comments, also adding the exceptions to others DAO's methods

* feat: new servlet; administrators now can sign up students

* feat: new servlet; administrators now can sign up students

* fix: improve input validation and treats unique violation

* fix: Make strings and variables dynamic

* feat(exceptions): adding exceptions to catch possible errors

* feat: fixing some comments, also adding the exceptions to others DAO's methods

* feat(exceptions): fixing some comments that talk abou things that I did not recognize in first moment

* merging

* feat: solving some prblems with create user and link to school class

* feat(exceptions): adding java doc to a method

* feat(schoolClassTeacher): creating a model for that table, also creating  a DAO

* feat(exceptions): adding exceptions to catch possible errors

* feat: fixing some comments, also adding the exceptions to others DAO's methods

* feat: solving some prblems with create user and link to school class

* feat(exceptions): solving the last comments

* feat(exceptions): merging with develop and fixing some things

* chore: trying to merge with develop

* feat(exceptions): adding exceptions to catch possible errors

* feat: fixing some comments, also adding the exceptions to others DAO's methods

* feat: new servlet; administrators now can sign up students

* feat: new servlet; administrators now can sign up students

* fix: improve input validation and treats unique violation

* fix: Make strings and variables dynamic

* feat: solving some prblems with create user and link to school class

* feat: creating servlets to find many students to teacher and to admin

* feat(admin/teacher): adding a servlet in admin to see all classes

* fix(teacher): moving servlet to a package of find many

* feat: solving some comments, also adding a java doc in student dao

* feat: passsing a servlet to a specific package

* feature: Add feedbacks dashboard and bulletin view (#64)

* feat: add feedbacks dashboard

* fix: improve pagination logic

* fix: remove testing logs

* feat: add bulletin view

* fix: improve constants usage, redirect logic and simplify the code

* fix: fix pagination bug: Infinity amount of pages

* Fix: compilation error: feature/59 (#68)

* feat: add feedbacks dashboard

* fix: improve pagination logic

* fix: remove testing logs

* feat: add bulletin view

* fix: improve constants usage, redirect logic and simplify the code

* fix: fix pagination bug: Infinity amount of pages

* fix: totalCount() signature

* fix: totalCount() signature

* fix: findMany()'s signature

* feat: adding Dockerfile to be able to run project in Render

* feat(render): changing some configurations to use only java JDK 19

* fix: making changes in version again

* feat(render): finidhing config, and changing input ype of cpf from number to text

* feat(render): adding a

* solving commit of /

* fix: fixig some problems with code and with maven

* fix: removing souts

* fix: fixing a problem in validation if the user is admin, teacher or student in forgotPassword send code and login of teacher and student

* feat(teacher): creating a servlet to return all data necessarily by teacher's home page

* feat: creating servlets to find many students to teacher and to admin

* feature: Add feedbacks dashboard and bulletin view (#64)

* feat: add feedbacks dashboard

* fix: improve pagination logic

* fix: remove testing logs

* feat: add bulletin view

* fix: improve constants usage, redirect logic and simplify the code

* fix: fix pagination bug: Infinity amount of pages

* feat(teacher): creating a servlet to return all data necessarily by teacher's home page

* feat: creating servlets to find many students to teacher and to admin

* feat(teacher): creating a servlet to return all data necessarily by teacher's home page

* feat(teacher): solving some comments

* feat: fixing some comments

* feat: addind output format and fixigng a possible problem

* chore: fixing merging problems

* feat(admin): adding a dao and model to school_class_subject and using that in add student

* feat: making some changes to fix problems with merge

* feat: fixing comment about status code 500

* feat: fixing some comments

* feat(admin): creating servlets and jsp to find many, create and update subjects

* feat: adding a validation before converting id to update

* feat(admin): improving validations and adding a input hidden

* fix: solving some mistakes that occured during the development process

* feat(admin): solving some problems with update subject

* feat(admin): solving mari's comments, such as fixing jsp's titles

* Create servlets for admin to create, list, or edit teachers #63 

* feat(admin): create servlet for admin find many teachers

* feat(admin): creating servlets to insert teacher and to find many teachers

* feat: add servlet that makes admin insert teachers

* feat: add servlet that make admin update teachers and fixing things

* fix: fixing JavaDoc

* fix: fixing the mistakes and adding the update/teacher.jsp

* refactor: changing the redirection

* refactor: changing the redirection

* fix: fixing caio's coments

* feat: add the email on the update servlet

* fix: fixing the update servlet

* refactor: improve findMany and details flow

* feat: add validateIdsExist method

* fix: fixing the treament of exceptions

* refactor: use createMany with batch insert for teacher associations

* fix: fix the name of the details/teacher.jsp file

* fix: improve error handling and redirect flow in teacher servelts

* refactor: add createMany and deleteMany into update servlet

* feat: add stylesheet to the find-many teacher.jsp

* fix: fixing caio's coments

* refactor: replace a JSP file entry in webContexts.xml

* fix: fix the verification of duplicate email and username

* fix: fix the verification of duplicate email and username on the insert servlet

---------

Co-authored-by: Caio Marcos <caio.maciel@germinare.org.br>

* feat: integrate styling  into student's flow (#88)

* refactor(teacher): changing the return of fin many students for teacher

* refactor: fixing the page of find many students

* refactor: finish the refactor of find many students

* feat: fixing some style and some querys

* feat: solving copilot comments

* feat: creating routes to create or update school_class

* feat: making little changes

* feat: adding udpate, delete and create to school_class

* feat: solving a problem

* feat: solving comments

* feat: add system to update student (#83)

* fix: resolve compilation error

* feat: add system to release grades

* fix: include access validation

* [WIP] Add system to update student information (#84)

* Initial plan

* fix: add ASCII encoding and length validation to validateName

Co-authored-by: EduardoCosta942 <112218438+EduardoCosta942@users.noreply.github.com>

---------

Co-authored-by: copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>
Co-authored-by: EduardoCosta942 <112218438+EduardoCosta942@users.noreply.github.com>

* fix: break servlet if AccessValidation.isAdmin(Request, Response) is false

* fix: use <a> tags for get methods

* fix: rename method in order to improve  consistency

* fix: change UpdateStudentServlet's path

* fix: fixed logic (I really do not know how the hell the code was like that)

---------

Co-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>

* feat: add route to release grades (#101)

* feat: add route to release grades

* fix: adjust inconsistencies

* fea(login): adding css in login and forgot password, also fixing some thigs in servlets

* feat: fixing some things, as passing styles to css

* feat: fixing some thing in find many teacher's style

* feat: adding style to find manys

* feat: adding a change my profile in jsp

* feat: add styling to insert pages (#97)

* feat: add styling to insert pages

* fix: instead of showing errors with JS, they are displayed  as text

* feat(admin): style details and update teacher part (#99)

* style(admin): style details and update teacher part

* refactor:remove unnecessary comments

* fix: closing the element <div>

---------

Co-authored-by: Mariana Marrão <marimarrao0115@gmail.com>

* feat: integrate styling  into student's flow (#88)

* feat: solving copilot comments

* feat: creating routes to create or update school_class

* feat: making little changes

* feat: adding udpate, delete and create to school_class

* feat: solving a problem

* fea(login): adding css in login and forgot password, also fixing some thigs in servlets

* feat: fixing some things, as passing styles to css

* feat: adding style to find manys

* feat: adding a change my profile in jsp

* feat: adding delete subject

* feat: solving some problems

* feat: fixing some routes

* chore: finishing to solve some merge problems

* Feature/105 (#111)

* feat: add styling for school_class' update

* feat: finalizando logo esse treco...

* feat: adding redirect to prod

* feat: adding error 500 page

* feat: add styling to findMany students page (#115)

* feat: add styling to findMany students page

* fix table

* fix sidebar

* Create SignUp Servlet for Students

* Finishing SighUpServlet and creating signup.jsp

* Fixing java exceptions

* Fixing linking from email to sign up page for students

* Fixing errors and adding a new jsp

* Putting dotenv methods in PostgreConnection and EmailService

* starting merge

* feat: fixing some things

* feat: add styling to teacher's homepage. (#103)

* fea(login): adding css in login and forgot password, also fixing some thigs in servlets

* feat: fixing some things, as passing styles to css

* feat: fixing some thing in find many teacher's style

* feat: adding style to find manys

* feat: adding a change my profile in jsp

* feat: add stylesheets to teacher's home page

* fix: fix path to findMany student

* refactor: remove the obs advice

* refactor(teacher): add a message in the homepage

* refactor: remove history in the sidebar.

* merge: fixing problems

---------

Co-authored-by: Caio Marcos <caio.maciel@germinare.org.br>

* feat: adding file to connect to postgresql database and creating files to make all folders tracked

* feat: changing commments to English not in pt-br

---------

Co-authored-by: Caio Marcos <caio.maciel@germinare.org.br>
Co-authored-by: Mariana Marrão <marimarrao0115@gmail.com>
Co-authored-by: Eduardo Costa <112218438+EduardoCosta942@users.noreply.github.com>
Co-authored-by: Mezini <caio.mezini09@gmail.com>
Co-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>